---
title: "R_Sample_Code"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
```{r setup, include=FALSE}
library(mongolite)
library(dplyr)
library(stringr)
library(reshape2)
library(igraph)
```


```{r}
client <- mongo(collection="Posts", db="stats_stackexchange_com", url="mongodb://yida:yida@0.tcp.ngrok.io:14162/admin")
#posts = client$find('{"@PostTypeId": "1"}', limit=100)
# posts
```

```{r}  

splitTags = function(x){
    tags = str_match_all(x, "<(.+?)>")[[1]][,2]
    if(length(tags)<=1){
        return()
    }
    edges_list = combn(tags, 2)
    return(edges_list)
}

posts = client$find('{"@PostTypeId": "1"}', limit=4000)
tags = posts$`@Tags`
tags = lapply(tags, splitTags)

el = matrix(unlist(tags), ncol=2, byrow=T)
g = make_graph(t(el), directed=F)
# -------------
adj_matrix = get.adjacency(g,sparse=FALSE)
del = c()
for(i in 1:dim(adj_matrix)[1]){
    if (sum(adj_matrix[i,])<200){
        del = c(del, i)
    }
}
adj_matrix = adj_matrix[-del, -del]
g = graph_from_adjacency_matrix(adj_matrix, mode = c("undirected"), weighted=TRUE)
E(g)$width <- E(g)$weight/max(E(g)$weight) * 10
d = sna::degree(adj_matrix)

# ------------
plot(g, 
     layout=layout.circle(g),
     vertex.size = d / max(d) * 50,
     edge.curved = T,
     vertex.label.font=2	,
     vertex.label.dist = 0.3	,
     vertex.label.cex	= 2
     )

```



```{r,include=F}
# library(sparklyr)
# library(dplyr)
# 
# 
# Sys.setenv(SPARK_HOME="C:\\Users\\yyin4\\AppData\\Local\\rstudio\\spark\\Cache\\spark-1.6.2-bin-hadoop2.6")
# Sys.getenv("SPARK_HOME")
# sc = spark_connect("local")
```





